#
# $Id: Makefile,v 1.2 1998/04/22 05:09:52 gdr-ftp Exp $
#
# Devin Reade, 1997
#

# Program name
PROG	= mkso

# Add -D__STACK_CHECK__	to print, on exit, the amount of stack used
CFLAGS	+= # -D__STACK_CHECK__
STACK	= 1024
BINDIR	= /sbin
CHAPTER	= 8

.INCLUDE:	/src/gno/prog.mk
