#
# $Id: Makefile,v 1.1 1997/12/21 22:39:13 gdr Exp $
#
# Devin Reade, 1997
#

# Program name
PROG	= mkso

# Add -D__STACK_CHECK__	to print, on exit, the amount of stack used
CFLAGS	+= # -D__STACK_CHECK__
STACK	= 1024
BINDIR	= /sbin

.INCLUDE:	/src/gno/prog.mk
