.\" Copyright 1996-1997 Devin Reade <gdr@myrias.com>
.\"
.\" $Id: inst.1,v 1.2 1997/10/30 04:14:21 gdr Exp $
.\"
.TH INSTALL 1 "16 October 1997" GNO "Commands and Applications"
.SH NAME
install \- copy files and set their attributes
.SH SYNOPSIS
.BR install
[
.I options
] [
.BR -s
]
.I source
.I dest
.br
.BR install
[
.I options
] [
.BR -s
]
.I source
[ ... ]
.I directory
.br
.BR install
[
.I options
]
[
.BR -d
]
.I directory
[ ... ]
.SH DESCRIPTION
.BR install
copies files and sets their permission modes and, if possible, their
owner and group.  It is used similarily to
.BR cp (1);
typically used in Makefiles to copy programs into their destination
directories.  It can also be used to create the destination directories
and any leading directories, and to set the directories modes.
.LP
Some of the options listed below are not implemented or are implemented
in a restricted sense.  Such options are recognised to maximize
.BR install 's
compatibility with other UNIX versions, in order to minimize problems
with ported shell scripts and makefiles.  Where options are not fully
implemented, it is usually due to differences between UNIX and GS/OS.
.SH OPTIONS
.IP \fB-c\fR
Ignored.  This option is included for backwards compatibility
with old UNIX versions of
.BR install .
.IP \fB-d\fR
Create each given directory and its leading directories, if they
do not already exist.
.IP "\fB-g\fR \fIgroup\fR"
Set the group ownership of the installed file or directory to the group
ID of
.I group
(default is the processes' current group).
.I group
may also be a numeric group ID.
.sp
\fBThis is currently ignored under GNO.\fR
.IP \fB-h\fR
Show usage information and exit.
.IP "\fB-m\fR \fImode\fR"
Set the permission mode for the installed file or directory to
.IR mode ,
which can be either an octal number, or a symbolic mode as in the
UNIX chmod command,
with 0 as the point of departure.  The default mode is 0755.
.sp
Note that currently under GNO, the
.I mode
is interpreted in the traditional UNIX sense in that it only affects
read, write, and (to a limited extent) execute permissions.
Furthermore, the only bits interpreted are those for the
user permissions; the
.I mode
is effectively bitwise `anded' with the constant 0700.
.sp
An execute modification is only permitted when the original file
is of type TXT or SRC, in which case the file becomes a shell script
(type SRC, auxtype 0x0006).  See also
.BR chmod (2).
.IP "\fB-o\fR \fIowner\fR"
If run as root, set the ownership of the installed file to the user ID of
.IR owner .
.I owner
may also be numeric user ID.
.sp
\fBThis is currently ignored under GNO.\fR
.IP \fB-s\fR
Strip the symbol tables from the installed programs.
.sp
\fBThis is currently ignored under GNO.\fR
.IP \fB-v\fR
Show version number.
.SH VERSION
This manual page documents
.BR install
version 1.1.
.SH AUTHOR
Devin Reade <gdr@eddore.myrias.com>
.SH "SEE ALSO"
.BR cp (1)
.BR chmod (2).
