.\"
.\" Devin Reade, February 1997
.\"
.\" $Id: intro.6,v 1.1 1997/02/27 07:32:29 gdr Exp $
.\"
.TH INTRO 6 "2 February 1997" GNO "Games"
.SH NAME
intro \- introduction to games
.SH DESCRIPTION
This chapter describes games.  Traditionally, these have been kept
separate from user programs.  GNO follows this convention.
.LP
Games are normally kept in the directory
.BR /usr/games .
Those that require configuration files should have such files in
.BR /usr/games/lib .
The directories
.BR /usr/lib
and
.BR /usr/local/lib
have also been used on occasion, but this is discouraged.
.LP
The manual page syntax of this chapter conforms to that of Chapter 1,
.IR "Commands and Applications" .
.LP
Most games described in this chapter will be text-oriented.
.SH SEE ALSO
.BR intro (1)
