#
# Makefile for netdb
#
# $Id: Makefile,v 1.4 1998/02/17 00:35:18 gdr-ftp Exp $
#

LIB=	netdb
SRCS=	rcmd.c getnetbyname.c getnetbyaddr.c getnetent.c getprotoname.c \
	getproto.c getprotoent.c getservbyname.c getservbyport.c \
	getservent.c gethostnamadr.c sethostent.c inet_addr.c inet_lnaof.c \
	inet_makeaddr.c inet_netof.c inet_network.c inet_ntoa.c res_comp.c \
	res_debug.c res_init.c res_mkquery.c res_query.c res_send.c \
	herror.c writev.c

OPTIMIZE=79

.INCLUDE: /src/gno/lib/lib.mk
