.\" Copyright (c) 1993-1994 Soenke Behrens
.\" $Id: udl.1,v 1.1 1994/12/13 18:08:26 gdr Exp $
.TH UDL 1 "22 November 1994" "Version 1.13" "Commands and Applications"
.SH NAME
udl - convert text files between different architectures
.SH SYNOPSIS
.BR udl
.BR -u | m | g
[
.B -Rv
]
.I file1 
[
.IR file2 " ..."
]
.SH DESCRIPTION
.B udl
converts files between different computer systems by changing the EOL
(End-Of-Line) character. It does
.I not
do a plausability check, so the user has to make sure udl is not invoked
on object files or the like.
.PP
.B udl
creates a temporary file the size of the file it is currently working on
while it's doing its thing.
.PP
When running under Byteworks' ORCA shell, the Orca shell wildcards
.BR =
and
.BR ?
are properly expanded in file names.
.SH OPTIONS
.IP \fB\-u\fP
Convert to use LF as EOL (Unix/Amiga).
.IP \fB\-m\fP
Convert to use CR/LF as EOL (MS-DOS).
.IP \fB\-g\fP
Convert to use CR as EOL (Apple).
.IP \fB\-p\fP
Be pedantic, only affects Unix<->Apple conversions, see below.
.IP \fB\-R\fP
Recurse through subdirectories.
.IP \fB\-v\fP
Be verbose, show the file udl is currently working on.
.PP
If you specify the
.B -p
switch,
.B udl
is pedantic while doing the conversion. This means: The input file may
contain bytes with a value of zero (0), and the input file may contain
different EOL characters (i.e., MS-DOS and Unix style might be mixed in
one file). For conversions to or from MS-DOS,
.B udl
is always pedantic, so this only affects conversions from Unix to Apple
or vice versa. Being pedantic slows udl down by a factor of 1.5.
.PP
If
.B udl
is given a file that seems to be a binary file \(that is, no EOL is
found in the first part of the file\), the file will be skipped.  No
notice is given of this unless the
.B -v
flag is used.
.SH BUGS
When compiling on some Solaris installations, files within subdirectories
do not get their names properly resolved.
This seems to be due to bad definitions in
.IR <sys/stat.h> .
If you have access to SunOS 4.x,
.BR udl
can be compiled there and used under Solaris.
.LP
If you find any other bugs, please send a report to the address given below.
.SH AUTHOR
Soenke Behrens, soenke.behrens@conner.com
.br
Version 1.13 updated by Devin Reade, gdr@myrias.ab.ca
.SH VERSION
This is
.B udl
version 1.13.
.br
It's 1.5 times faster than 1.1 for Unix<->Apple conversions.
