char    *hookup         (char *host, int port);
char    *getlogin       (void);
int      login          (char *host);
void     cmdabort       (int sig, int code);
int      command        (char *string, ...);
int      getreply       (int expecteof);
int      empty          (struct fd_set *mask, int sec);
void     abortsend      (int sig, int code);
void     sendrequest    (char *cmd, char *local, char *remote, int printnames);
void     abortrecv      (int sig, int code);
void     recvrequest    (char *cmd, char *local, char *remote, char *lmode, int printnames);
int      initconn       (void);
FILE    *dataconn       (char *lmode);
void     ptransfer      (char *direction, long bytes, struct timeval *t0, struct timeval *t1);
void     tvsub          (struct timeval *tdiff, struct timeval *t1, struct timeval *t0);
void     psabort        (int sig, int code);
void     pswitch        (int flag);
void     abortpt        (int sig, int code);
void     proxtrans      (char *cmd, char *local, char *remote);
char    *gunique        (char *local);
void     abort_remote   (FILE *din);
