.\" Copyright (c) 1989, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)getlogin.2	8.1 (Berkeley) 6/9/93
.\"
.TH GETLOGIN 2 "17 September 1997" GNO "System Calls"
.SH NAME
.BR getlogin ,
.BR setlogin
\- get/set login name
.SH SYNOPSIS
#include <unistd.h>
.sp 1
char *\fBgetlogin\fR (void);
.sp 1
int \fBsetlogin\fR (const char *\fIname\fR);
.SH DESCRIPTION
The
.BR getlogin 
routine
returns the login name of the user associated with the current session,
as previously set by
.BR setlogin .
The name is normally associated with a login shell
at the time a session is created,
and is inherited by all processes descended from the login shell.
(This is true even if some of those processes assume another user ID,
for example when
.BR su (1)
is used.)
.LP
.BR Setlogin 
sets the login name of the user associated with the current session to
.IR name .
This call is restricted to the super-user, and
is normally used only when a new session is being created on behalf
of the named user
(for example, at login time, or when a remote shell is invoked).
.SH RETURN VALUES
If a call to
.BR getlogin 
succeeds, it returns a pointer to a null-terminated string in a static buffer.
If the name has not been set, it returns
.BR NULL .
If a call to
.BR setlogin 
succeeds, a value of 0 is returned.  If
.BR setlogin 
fails, a value of -1 is returned and an error code is
placed in the global location
.IR errno .
.SH ERRORS
The following errors may be returned by these calls:
.RS
.IP \fBEFAULT\fR
The
.I name
parameter gave an
invalid address.
.IP \fBEINVAL\fR
The
.I name
parameter
pointed to a string that was too long.
Login names are limited to
.BR MAXLOGNAME
(from
.BR <sys/param.h> )
characters, currently 12.
.IP \fBEPERM\fR
The caller tried to set the login name and was not the super-user.
.RE
.SH SEE ALSO
.BR setsid (2)
.SH BUGS
Login names are limited in length by
.BR setlogin .
However, lower limits are placed on login names elsewhere in the system
.RB ( UT_NAMESIZE
in
.BR <utmp.h> ) .
.LP
In earlier versions of the system,
.BR getlogin 
failed unless the process was associated with a login terminal.
The current implementation (using
.BR setlogin )
allows getlogin to succeed even when the process has no controlling terminal.
In earlier versions of the system, the value returned by
.BR getlogin 
could not be trusted without checking the user ID.
Portable programs should probably still make this check.
.SH HISTORY
The
.BR getlogin 
function first appeared in 4.4BSD.
