.\"
.\" Undocumented system calls.
.\" Devin Reade, 1997
.\"
.\" $Id: undocumented.2,v 1.1 1997/02/27 07:32:17 gdr Exp $
.\"
.TH UNDOCUMENTED 2 "16 January 1997" GNO "System Calls"
.SH NAME
.BR InstallNetDriver ,
.BR SetGNOQuitRec ,
.BR kvm_close ,
.BR kvm_getproc ,
.BR kvm_nextproc ,
.BR kvm_open ,
.BR kvm_setproc ,
.BR kvmgetproc ,
.BR kvmnextproc ,
.BR kvmsetproc ,
.BR setsystemvector
\- undocumented system calls
.SH DESCRIPTION
The system calls on this page do not have documentation at this time.
Questions regarding these routines should be forwarded to Procyon.
