.\"
.\" $Id: catrez.1,v 1.3 1997/09/30 05:14:47 gdr Exp $
.\"
.TH catrez 1 "September 1997" GNO "Commands and Applications"
.SH NAME
catrez \- concatenate resource forks from files
.SH SYNOPSIS
.BR catrez " [" -av ]
.BI "-d " dest_file
.I file1
[
.IR file2 ...
]
.SH DESCRIPTION
.B catrez
concatenates resources from multiple files into the resource fork of a
single file. (The data fork of the destination file is not modified.)
This is useful to programmers who create
resources for a program in several different files and need to combine
them into the resource fork of the final executable file.
.SH OPTIONS
.IP \fB-v\fR
Produce verbose output, including: the program version,
the name of each source file, the type & ID of each copied resource, and
whether a resource converter is required.
.IP \fB-a\fR
Append resources to the destination file rather than overwriting the
resource fork.
.IP "\fB-d\fR \fIdestfile\fR"
Existing destination file name [required parameter].
.SH "GNO COMPATIBILITY"
.B catrez
will shut itself down if it receives any of the following signals:
.RS
.nf

\fBSIGHUP\fR  (hang-up),
\fBSIGINT\fR  (user keyboard interrupt),
\fBSIGPIPE\fR (writing to a pipe with no reader),
\fBSIGALRM\fR (alarm timer expiration), or
\fBSIGTERM\fR (kill).

.fi
.RE
User signals
.RB ( SIGUSR1
and
.BR SIGUSR2 )
are ignored.
.SH EXAMPLES
Append the resources from menu.r to the resource fork of progfile:
.RS
catrez -a -d progfile menu.r
.RE
.LP
Combine several resource files and add to progfile
.RS
catrez -d progfile version.r menu.r window.r startup.r
.RE
.SH VERSION
This manual page documents
.BR catrez
version 1.0.2.
.SH "RETURN VALUES"
.B catrez
returns zero on success, non-zero otherwise.
.SH AUTHOR
Dave Tribby <tribby@cup.hp.com>
.SH HISTORY
Version 1.0 was released as an independent utility compatible with
GNO in July 1996. Version 1.0.1, released in November 1996, fixed a
problem with "protected" attributes. Version 1.0.2 was updated
in September 1997 to use GNO 2.0.6 headers, libraries, and coding
conventions, and released as part of GNO 2.0.6.
