#
# This makefile is intended for use with dmake(1) on Apple IIGS
#
# $Id: Makefile,v 1.2 1997/09/26 06:30:33 gdr Exp $
#

# Program name
PROG	= catrez

# Delivery directory
BINDIR	= /usr/bin
STACK	= 768

.INCLUDE:	/src/gno/prog.mk
