.\"
.\" Devin Reade, January 1997
.\"
.\" $Id: intro.4,v 1.1 1997/02/27 07:32:28 gdr Exp $
.\"
.TH INTRO 4 "12 January 1997" GNO Devices
.SH NAME
intro \- introduction to device drivers
.SH DESCRIPTION
This chapter describes GNO device drivers.
.LP
Note that device drivers under GNO are referenced by the GS/OS convention
of using a preceeding dot (such as
.BR .tty ).
This differs from other Unix implementations that use device files in the
.BR /dev
directory.
.SH SEE ALSO
.IR "GNO Kernel Reference Manual" ,
.br
.IR "GNO Shell (gsh) Reference Manual" .
