.\"
.\"     $Id: getvers.1,v 1.3 1998/05/08 17:33:41 tribby Exp $
.\"
.TH GETVERS 1 "April 1998" "GNO" "Commands and Applications"
.SH NAME
.LP
.B getvers
\- list information stored in rVersion and rComment resources
.SH SYNOPSIS
.BR getvers " [" -b "] [" -c "]"
.RB "[" -f "] [" -q "] file ..."
.SH DESCRIPTION
.BR getvers
print the version information (product name, version, description, country)
stored in the rVersion resource of the specified files and optionally print
the contents of the rComment resource. If there is no version information,
or if there is an error accessing the file,
.BR getvers
prints a message and continues processing any remaining files.
.LP
To add rVersion resource information to a file, you can use the companion
shell utility
.IR setvers (1),
or use the
.IR rez
resource compiler.
.PP
.BR getvers
returns 1 to its parent program if an error is encountered processing
any of the files. Otherwise it returns 0.
.SS OPTIONS
.BR getvers
recognizes these options:
.IP \fB-b\fR
print a brief one-line listing for each file, showing only the product
name and version.
.IP \fB-c\fR
print rComment resource number 1 (the one displayed by Finder in
file information windows).
.IP \fB-f\fR
print the name of a file before printing its information.
.IP \fB-q\fR
do not print error or warning information.
.SH SEE ALSO
.IR setvers "(1)"
.SH VERSION
This manual page documents
.BR getvers
version 2.0.
.SH AUTHOR
Originally written by Ian Schmidt, Two Meg Software. Updated by Dave Tribby
for  GNO/ME 2.0.6.
.SH HISTORY
The previous version (1.20) of
.BR getvers
was released by Ian Schmidt in May 1993
as an independent archive compatible with GNO and ORCA.
