.TH VERSION 1
.SH NAME
.LP
.B gv
\- get version number and information stored in rVersion format from
specified executable file and print in shorter format.
.SH SYNOPSIS
.LP
.BR gv  " <  file1 file2 ...filen  >"
.SH DESCRIPTION
.LP
.B gv
is a program which accepts as input the name(s) of any number of file(s)
and print only the version number stored in the rVersion resource of
the file(s).  If no rVersion resource is present it will print the error
`The file <filename> has no version resource' and process any remaining files.
.LP
To add information to the rVersion resource, you can use the companion
shell utility
.BR setvers "."
.LP
You can use the companion shell utility
.BR getvers " to list versions in a more complete form."
.SH BUGS
.LP
Unpredictable results may occur if a file's rVersion resource is damaged.
Other exception cases should be correctly handled.
.SH SEE ALSO
.LP
.BR setvers "(1)"
.BR getvers "(1)"
.SH AUTHOR
.LP
.nf
Ian Schmidt, Two Meg Software

internet  irsman@iastate.edu
BITNET    twbv4@isuvax
AOL       IRSMan
.fi
