#
# gno/lib/libc/locale/Makefile
#
# Devin Reade, 1997
#
# $Id: Makefile,v 1.2 1997/09/05 06:15:49 gdr Exp $
#

.INCLUDE:	../../../paths.mk
.INCLUDE: 	../../const.mk

OBJS	= table.o

default:	$(OBJS)

.INCLUDE:	../rules.mk
