#
# gno/lib/libc/locale/Makefile
#
# Devin Reade, 1997
#
# $Id: Makefile,v 1.3 1997/09/21 06:10:26 gdr Exp $
#

.INCLUDE:	../../../paths.mk
.INCLUDE: 	../../const.mk

OBJS	= table.o
CFLAGS	+= -O78

build:	../libc
obj:	$(OBJS)

.INCLUDE:	../rules.mk
