.\"
.\" Devin Reade, February 1997
.\"
.\" $Id: intro.5,v 1.1 1997/02/27 07:32:29 gdr Exp $
.\"
.TH INTRO 5 "2 February 1997" GNO "File Formats"
.SH NAME
intro \- introduction to file formats
.SH DESCRIPTION
This chapter describes the format of various special files used by
GNO.  Many of these will be text files that can be modified for
specific site configurations.  Others will describe file types that
cannot be modified with impunity.
.LP
Most standard IIgs file types do not have manual pages written for
them.  Instead, the base documents listed in the
.BR "SEE ALSO"
section should be consulted.
.SH SEE ALSO
.IR "Apple IIgs GS/OS Reference" ,
.br
.IR "Inside Macintosh:  Files" ,
.br
.IR "Orca/M Reference Manual" ,
.br
.IR "Programmer's Reference Manual for System 6.0/6.0.1" ,
.br
Apple DTS (Developer Technical Support)
.IR "Technical Notes"
and
.IR "File Type Notes" .
