#	@(#)Makefile	8.1 (Berkeley) 6/6/93
#	$Id: Makefile,v 1.2 1998/03/11 03:02:17 gdr-ftp Exp $

PROG=	ctags
SRCS=	ctags.c C.c fortran.c lisp.c print.c tree.c yacc.c
STACK=	2048
HAS_BSD_MANPAGE	= true
BINDIR		= /usr/bin

.INCLUDE: /src/gno/prog.mk
