#	@(#)Makefile	8.1 (Berkeley) 6/6/93
#	$Id: Makefile,v 1.1 1998/01/24 07:58:57 taubert Exp $

PROG=	ctags
SRCS=	ctags.c C.c fortran.c lisp.c print.c tree.c yacc.c
STACK=	2048

.INCLUDE: /src/gno/prog.mk
