#
# This makefile is intended for use with dmake(1) on Apple IIGS
#
#	Created by Dave Tribby, August 1997
#
# $Id: Makefile,v 1.2 1997/09/26 06:34:18 gdr Exp $

# Program name
PROG=	cut

# Delivery directory
BINDIR	= /usr/bin

.INCLUDE:	/src/gno/prog.mk
