.TH LAUNCH 1 "22 December 1997" GNO "Commands and Applications"
.SH NAME
launch \- adds application to the GS/OS quit stack
.SH DESCRIPTION
.B launch
programs that are not fully compatible wth GNO, such as ProSEL 16 and ProDOS 8 applications.
.LP
Once it's added to the quit stack, you can execute the program by
.BR "exit" " if you ran gsh straight from initrc.  If you are using init,"
.RB "type " "init 5" ". "
You will probably want to make aliases for them in gshrc for convenience.
.SH SYNOPSIS
.BR launch " [-n] <filename>"
.LP
.BR filename " is the full path name of program -- no namespace."
.LP
.BR -n " do not add GNO to the quit stack; upon exiting the launched"
application, you will return to the application that launched GNO.
.SH EXAMPLES
alias pt 'launch /diskname/proterm/pt3.system;exit'
.br
alias pt 'launch /diskname/proterm/pt3.system;init 5'
.SH AUTHOR
.LP
.nf
Jawaid Bazyar (bazyar@cs.uiuc.edu)
.fi
