.\" This man page was written to conform with the lenviron v1.1.3
.\" release for Gno v2.0.3 and later by Devin Reade.
.\"
.\" $Id: buildEnv.3,v 1.1 1997/02/27 07:32:21 gdr Exp $
.\"
.TH BUILDENV 3 "30 January 1997" GNO "Library Routines"
.SH NAME
buildEnv - add a vector of strings to the process environment
.SH SYNOPSIS
#include <gno/gno.h>
.sp 1
int \fBbuildEnv\fR (char * const *\fIenvp\fR);
.SH DESCRIPTION
.BR buildEnv
takes takes a NULL-terminated array of character string pointers,
where each string is of the format
.I NAME=VALUE
and adds the strings to the process environment via
.BR putenv (3).
.SH RETURN VALUE
.B buildEnv
returns zero on success.  On failure, it returns -1 and sets
.IR errno .
.SH HISTORY
This routine was originally called
.BR build_env
and was part of the 
.BR lenviron
library written by Devin Reade for GNO v2.0.3 in April 1994.
It was incorporated into the GNO
.BR libc
as of v2.0.6.
.SH SEE ALSO
.BR buildCmd (3),
.BR buildPath (3),
.BR environ (7).
