.\"
.\" Devin Reade, January 1997
.\"
.\" $Id: Intro.3,v 1.1 1997/02/27 07:32:20 gdr Exp $
.\"
.TH INTRO 3 "12 January 1997" GNO "Library Routines"
.SH NAME
Intro \- Introduction Library Functions
.SH DESCRIPTION
This chapter describes library functions.  These are routines which do
not directly access the GNO kernel.
.LP
The
.BR SYNOPSIS
section of each manual page gives the prototype for the function(s)
described, along with a listing of the header files which provide
the prototypes.  The sequence of header file inclusion may be important,
so they should be included in the sequence given.
.LP
The 
.BR DESCRIPTION
section gives the detailed description of the function.
Note that since functions in this section are not system calls, you
cannot in general assume that the global integer variable
.BR errno
will be relevent to any error condition.  The only way to detect an
error condition is to use the mechanism, if any, described in the 
relevent manual page.
.SH "SEE ALSO"
There are many references for programming under GNO.  See the
Frequently Asked Questions (FAQ) list for the USENET newsgroup
comp.sys.apple.gno for a discussion on this topic.
