.\" Man page by Devin Reade.
.\"
.\" $Id: mapErr.3,v 1.1 1997/02/27 07:32:23 gdr Exp $
.\"
.TH "_MAPERR" 3 "21 January 1997" GNO "Library Routines"
.SH NAME
.BR _mapErr
\- map GS/OS error codes to UNIX errno codes
.SH SYNOPSIS
#include <gno/gno.h>
.sp 1
int
\fB_mapErr\fR(int \fIerr\fR);
.SH DESCRIPTION
.BR _mapErr 
takes a GS/OS error code
.IR err
(typically returned by
.BR toolerror (3)
or taken from the value of the global integer
.BR _toolErr )
and maps it to a UNIX error code suitable for use with
.BR perror (3) 
and related routines.
.LP
If 
.IR err
is zero, 
.BR _mapErr
returns zero.
If there is no direct mapping, then
.BR EIO
is returned.
.SH SEE ALSO
.BR perror (3),
.BR toolerror (3),
and the
.IR "GS/OS Reference Manual" .