#
# gno/lib/libc/string/Makefile
#
# $Id: Makefile,v 1.7 1999/09/01 01:02:13 gdr-ftp Exp $
#

LIB	= c
LIBPFX	= $(OBJ_DIR)../
NO_REZ	= true
SRCS	= case.c str.c strerror.c swab.c

.INCLUDE: /src/gno/lib/lib.mk
