#
# gno/lib/libc/string/Makefile
#
# Devin Reade, 1997
#
# $Id: Makefile,v 1.2 1997/09/05 06:33:22 gdr Exp $
#

.INCLUDE:	../../../paths.mk
.INCLUDE: 	../../const.mk

OBJS	= case.o str.o strerror.o

default:	$(OBJS)

.INCLUDE:	../rules.mk
