# makefile.mk generated by makedmake v0.22 (Gno v1.1)

# development flags:  Undefine __GNO__ to get a more Orca compatible version.
# CFLAGS  = -i -w -s1023 -G25 -DDEBUG -DCASEFLAG -D__GNO__
# LDLIBS  = /usr/lib/stack.a
# LDFLAGS = 

# distribution flags:  Undefine __GNO__ to get a more Orca compatible version.
CFLAGS  = -i -w -s1023 -O -DCASEFLAG -D__GNO__
LDLIBS  =
LDFLAGS = 


whereis			: whereis.o
	$(CC) $(LDFLAGS) -o whereis  whereis.o $(LDLIBS)

whereis.o		: whereis.c
	$(CC) $(CFLAGS) -c whereis.c

install			:
	/bin/cp -f Gno/whereis   /usr/bin
	/bin/cp -f Orca/whereis  17
	/bin/cp -f whereis.1 /usr/man/man1
