# Makefile.mk generated by makedmake (Gno) v1.1.1 for Dennis Vadura's dmake

BINDIR = 17
MANDIR = /usr/man

# development flags
# DEFINES   += -DDEBUG -DCASEFLAG
# CFLAGS    += -w -s1023 -G25 $(DEFINES)
# LDFLAGS   += 
# LDLIBS     = /usr/lib/stack.a

# distribution flags
DEFINES   += -DCASEFLAG
CFLAGS    += -w -s1023 -O $(DEFINES)
LDFLAGS   += 
LDLIBS     =

all:
	echo Targets ...
	echo
	echo dmake install ... to copy executable file to $(BINDIR) and manual
	echo page to $(MANDIR)
	echo
	echo dmake whereis ... to compile source code.  This should not be
	echo necessary.

whereis			: whereis.o
	$(CC) $(LDFLAGS) -o whereis  whereis.o $(LDLIBS)

whereis.o		: whereis.c
	$(CC) $(CFLAGS) -c whereis.c

install			:
	-$(RM) /usr/bin/whereis
	-$(RM) 17/whereis
	/bin/cp -f whereis   $(BINDIR)
	/bin/cp -f whereis.1 $(MANDIR)/man1

.SILENT: all
