.\"
.\" $Id: calendar.1,v 1.3 1998/07/07 02:14:29 gdr-ftp Exp $
.\"
.TH CALENDAR 1 "6 July 1998" GNO "Commands and Applications"
.SH NAME
.BR calendar
\- reminder service
.SH SYNOPSIS
calendar
.SH DESCRIPTION
.BR calendar
consults the file 
.B calendar
in the current directory
and prints out lines that contain today's or tomorrow's date
anywhere in the line.  Most reasonable month-day dates such as
.IR "Aug. 24" ,
.IR "august 24" ,
.IR "8/24",
and so on, are recognized, but not
.IR "24 August"
or
.IR "24/8" .
On weekends ``tomorrow'' extends through Monday.
.BR calendar
can be invoked regularly by using the
.BR crontab (1)
or
.BR at (1)
commands.
.SH EXAMPLE
A common way to run
.BR calendar 
is to have the following line in your 
.B gshrc
file:
.nf

	/usr/games/calendar

.fi
If the file $HOME/calendar contains entries like
.nf

	Dec 25	No more shopping days until Christmas.
	Jul 1	Dominion Day (Canada).

.fi
then the appropriate calendar entries will be printed every time you 
login in.
.SH CAVEATS
.BR calendar 's
extended idea of ``tomorrow'' does not account for holidays.
.SH "SEE ALSO"
.BR at (1),
.BR cron (1),
.BR crontab (1),
.BR date (1)
.SH AUTHOR
Written for GNO by Christopher Neufeld.
Updated by Marlin Allred.
