#
# $Id: Makefile,v 1.2 1998/10/31 19:02:47 gdr-ftp Exp $
#

PROG	= syslogd
MAIN	= syslogd2
SRCS	= syslogd2.c

CFLAGS	+= -D__STACK_CHECK__
STACK	= 4096
BINDIR	= /usr/sbin
CHAPTER	= 8

.INCLUDE:	/src/gno/prog.mk
