#
# $Id: Makefile,v 1.3 2012/08/26 02:54:59 gdr Exp $
#

PROG	= syslogd
MAIN	= syslogd2
SRCS	= syslogd2.c

CFLAGS	+= -D__STACK_CHECK__ -v
STACK	= 4096
BINDIR	= /usr/sbin
CHAPTER	= 8

.INCLUDE:	/src/gno/prog.mk
