#
# $Id: Makefile,v 1.2 1999/02/15 20:11:25 gdr-ftp Exp $
#

PROG	= newuser
SRCS	= newuser.c
LDADD	= -lcrypt -lcontrib
BINDIR	= /usr/sbin
CHAPTER	= 8

# observed stack usage: 944 bytes

HAS_MKSO_DATA	= true
HAS_MKLINK_DATA	= true

.INCLUDE: /src/gno/prog.mk
