.TH NEWUSER 8
.SH NAME
.nf
newuser  - add a new user to the system
newuserv - add a new user to the system, subject to validation
.fi
.LP
.SH DESCRIPTION
This is
.B newuser
for GNO/ME.  Its basic intent is
to let people add themselves to the system without requiring the system
administrator to do it all manually.
.LP
.B newuser
will ask for real name, account name, terminal type and password (verifying
the password once) and then create the directory /user/(account name) and
copy a template
.B gshrc
into that directory.  Then it will add the user to
.B /etc/passwd
and exit.
.PP
If the
.B -v
(verify) flag is selected, everything is done as normal, except
that the new entry is appended to
.B /var/adm/newuser/newusers
instead of being appended to
.BR /etc/passwd ". "
.LP
.SH FILES
.nf
.BR /var/adm/newuser/newid " -- This file holds the next available"
userID. newuser will increment it as necessary.
.BR /var/adm/newuser/gshrc " -- This is the 'template' gshrc file"
that all new users will get.  In addition to this, newuser will append
'set' commands to set $home and $user.
.BR /etc/passwd " -- Not required if you use -v.  But what's the point"
in newuser if you don't have it? :)
.BR /user/ " -- Has to exist.  This is where the user's home directories"
go.
.fi
.LP
.B newuser
will time out after 60 seconds of operation.
.LP
.SH AUTHOR
.nf
James Brookes
jamesb@cscihp.ecst.csuchico.edu
.fi
