#	@(#)Makefile	8.1 (Berkeley) 6/6/93
#	$Id: Makefile,v 1.3 1998/04/16 06:33:45 gdr-ftp Exp $

PROG=	whois
LDADD=	-lnetdb
OPTIMIZE=79
DEBUG=	25
BINDIR	= /usr/bin
HAS_BSD_MANPAGE	= true

.INCLUDE: /src/gno/prog.mk
