#
# gno/lib/libc/sys/Makefile
#
# $Id: Makefile,v 1.6 1998/02/19 01:07:56 gdr-ftp Exp $
#

LIB	= c
LIBPFX	= $(OBJ_DIR)../
NO_REZ	= true
SRCS	= exec.c syscall.c trap.asm

.INCLUDE: /src/gno/lib/lib.mk

trap.o:	trap.mac
