.\" Copyright (c) 1980, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Donn Seeley at Berkeley Software Design, Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)init.8	8.3 (Berkeley) 4/18/94
.\"
.\" $Id: init.8,v 1.1 1997/10/04 05:23:51 gdr Exp $
.\"
.TH INIT 8 "4 October 1997" GNO "System Administration"
.SH NAME
.BR init
\- process control initialization
.SH SYNOPSIS
.BR init
.SH DESCRIPTION
The
.BR init
program
is the last stage of the boot process.
It normally runs the automatic reboot sequence as described in
.BR reboot (8),
and if this succeeds, begins multi-user operation.
If the reboot scripts fail,
.BR init
commences single user operation by giving
the super-user a shell on the console.
The
.BR init
program may be passed parameters
from the boot program to
prevent the system from going multi-user and to instead execute
a single user shell without starting the normal daemons.
The system is then quiescent for maintenance work and may
later be made to go to multi-user by exiting the
single-user shell (with ^D).
This
causes
.BR init
to run the
.BR /etc/rc
start up command file in fastboot mode (skipping disk checks).
.LP
If the
.BR console
entry in the
.BR ttys (5)
file is marked ``insecure'',
then
.BR init
will require that the superuser password be
entered before the system will start a single-user shell.
The password check is skipped if the 
.BR console
is marked as ``secure''.
.LP
The kernel runs with four different levels of security.
Any superuser process can raise the security level, but only 
.BR init
can lower it.
Security levels are defined as follows:
.RS
.IP \fB-1\fR
Permanently insecure mode \- always run system in level 0 mode.
.IP \fB0\fR
Insecure mode \- immutable and append-only flags may be turned off.
All devices may be read or written subject to their permissions.
.IP \fB1\fR
Secure mode \- immutable and append-only flags may not be changed;
disks for mounted filesystems,
.BR /dev/mem ,
and
.BR /dev/kmem
are read-only.
.IP \fB2\fR
Highly secure mode \- same as secure mode, plus disks are always
read-only whether mounted or not.
This level precludes tampering with filesystems by unmounting them,
but also inhibits running
.BR newfs (8)
while the system is multi-user.
.RE
.LP
Normally, the system runs in level 0 mode while single user
and in level 1 mode while multiuser.
If the level 2 mode is desired while running multiuser,
it can be set in the startup script
.BR /etc/rc
using
.BR sysctl (8).
If it is desired to run the system in level 0 mode while multiuser,
the administrator must build a kernel with the variable
.BR securelevel
defined in the file
.BR /sys/compile/MACHINE/param.c
and initialize it to -1.
.LP
In multi-user operation, 
.BR init
maintains
processes for the terminal ports found in the file
.BR ttys (5).
.BR Init
reads this file, and executes the command found in the second field.
This command is usually
.BR getty (8);
.BR getty 
opens and initializes the tty line
and
executes the
.BR login 
program.
The
.BR login 
program, when a valid user logs in,
executes a shell for that user.  When this shell
dies, either because the user logged out
or an abnormal termination occurred (a signal),
the
.BR init
program wakes up, deletes the user
from the
.BR utmp (5)
file of current users and records the logout in the
.BR wtmp 
file.
The cycle is
then restarted by
.BR init
executing a new
.BR getty 
for the line.
.LP
Line status (on, off, secure, getty, or window information)
may be changed in the
.BR ttys 
file without a reboot by sending the signal
.BR SIGHUP
to
.BR init
with the command
.B "kill -HUP 1" .
On receipt of this signal,
.BR init
re-reads the
.BR ttys 
file.
When a line is turned off in
.BR ttys ,
.BR init
will send a SIGHUP signal to the controlling process
for the session associated with the line.
For any lines that were previously turned off in the
.BR ttys 
file and are now on,
.BR init
executes a new
.BR getty 
to enable a new login.
If the getty or window field for a line is changed,
the change takes effect at the end of the current
login session (e.g., the next time 
.BR init
starts a process on the line).
If a line is commented out or deleted from
.BR ttys ,
.BR init
will not do anything at all to that line.
However, it will complain that the relationship between lines
in the
.BR ttys 
file and records in the
.BR utmp 
file is out of sync,
so this practice is not recommended.
.LP
.BR Init
will terminate multi-user operations and resume single-user mode
if sent a terminate TERM
signal, for example,
.BR "kill \-TERM 1" .
If there are processes outstanding that are deadlocked (because of
hardware or software failure),
.BR init 
will not wait for them all to die (which might take forever), but
will time out after 30 seconds and print a warning message.
.LP
.BR Init
will cease creating new
.BR getty Ns's
and allow the system to slowly die away, if it is sent a terminal stop
TSTP signal, i.e.
.BR "kill \-TSTP 1" .
A later hangup will resume full
multi-user operations, or a terminate will start a single user shell.
This hook is used by
.BR reboot (8)
and
.BR halt (8).
.LP
.BR Init
will terminate all possible processes (again, it will not wait
for deadlocked processes) and reboot the machine if sent the interrupt
INT signal, i.e.
.BR "kill \-INT 1" .
This is useful for shutting the machine down cleanly from inside the kernel
or from X when the machines appears to be hung.
.LP
The role of
.BR init
is so critical that if it dies, the system will reboot itself
automatically.
If, at bootstrap time, the
.BR init 
process cannot be located, the system will panic with the message
``panic: "init died (signal %d, exit %d)''.
.SH DIAGNOSTICS
.RS
.IP "\fIgetty repeating too quickly on port %s, sleeping\fR"
A process being started to service a line is exiting quickly
each time it is started.
This is often caused by a ringing or noisy terminal line.
.IR "Init will sleep for 10 seconds" ,
.IR "then continue trying to start the process" .
.LP
.IP "\fIsome processes would not die; ps axl advised.\fR"
A process
is hung and could not be killed when the system was shutting down.
This condition is usually caused by a process
that is stuck in a device driver because of
a persistent device error condition.
.RE
.SH FILES
.RS
.IP \fB/dev/console\fR
System console device.
.IP \fB/dev/tty*\fR
Terminal ports found in
.BR ttys .
.IP \fB/var/run/utmp\fR
Record of Current users on the system.
.IP \fB/var/log/wtmp\fR
Record of all logins and logouts.
.IP \fB/etc/ttys\fR
The terminal initialization information file.
.IP \fB/etc/rc\fR
System startup commands.
.RE
.SH SEE ALSO
.BR login (1),
.BR kill (1),
.BR sh (1),
.BR ttys (5),
.BR crash (8),
.BR getty (8),
.BR rc (8),
.BR reboot (8),
.BR halt (8),
.BR shutdown (8)
.SH HISTORY
A
.BR init
command appeared in Version 6 AT&T UNIX.
.SH BUGS
Systems without
.BR sysctl 
behave as though they have security level \-1.
