.\"
.\" Devin Reade, March 1998
.\"
.\" $Id: link.1,v 1.1 1998/03/31 03:32:48 gdr-ftp Exp $
.\"
.TH LINK 1 "30 March 1998" GNO "Commands and Applications"
.SH NAME
link \- link a object files
.SH SYNOPSIS
\fBlink\fR [\fIoptions\fR] \fIobjectfile\fR ... [\fIqualifiers\fR]
.SH DESCRIPTION
.BR link
is the secondary front end to the ORCA Zaplink program.  (The primary
front end is
.BR occ (1)).
.LP
For a complete explanation of
.BR link
including a description of
.IR options
and
.IR qualifiers ,
see the chapter
.I "The Command Processor"
in any of the ORCA/C, ORCA/M, or ORCA/Pascal Reference Manuals.
.SH "SEE ALSO"
.BR compile (1),
.BR dmake (1),
.BR occ (1).
.br
.IR "ORCA/C Reference Manual" .
