.\"
.\" Devin Reade, February 1997
.\"
.\" $Id: intro.7,v 1.1 1997/02/27 07:32:30 gdr Exp $
.\"
.TH INTRO 7 "2 February 1997" GNO "Miscellaneous"
.SH NAME
intro \- introduction to miscellaneous information
.SH DESCRIPTION
This chapter contains manual pages which do not fit into any of the
other chapters' categories.
