.\" Copyright (c) 1980, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)fmt.1	8.1 (Berkeley) 6/6/93
.\"
.\" $Id: fmt.1,v 1.2 1997/09/21 22:12:26 gdr Exp $
.\"
.TH FMT 1 "2 August 1997" "GNO" "Commands and Applications"
.SH NAME
fmt \- simple text formatter
.SH SYNOPSIS
.BR fmt
[
.B -o
.I goal
[
.I maximum
]] [
.B -c
] [
.I "name ..."
]
.SH DESCRIPTION
.BR Fmt
is a simple text formatter which reads the concatenation of input
files (or standard input if none are given) and produces on standard
output a version of its input with lines as close to the
.I goal
length
as possible without exceeding the 
.IR maximum .
The
.I goal
length defaults to 65 and the 
.I maximum
to 75.  The spacing at the beginning of the
input lines is preserved in the output, as are blank lines and
interword spacing.
.LP
.BR Fmt
is meant to format mail messages prior to sending, but may also be useful
for other simple tasks.
For instance,
within visual mode of the
.BR ex (1)
editor (e.g.
.BR vi (1))
the command
.nf
	\&!}fmt
.fi
will reformat a paragraph,
evening the lines.
.SH SEE ALSO
.BR nroff (1),
.BR mail (1)
.SH HISTORY
The
.BR fmt
command appeared in 4.3BSD.
.SH AUTHOR
Kurt Shoens
.br
Liz Allen (Added goal length concept.)
.br
Devin Reade (Updated for GNO.)
.SH BUGS
The program was designed to be simple and fast \- for more complex
operations, the standard text processors are likely to be more appropriate.
