#	@(#)Makefile	8.1 (Berkeley) 6/6/93
#	$Id: Makefile,v 1.3 1998/04/16 06:33:39 gdr-ftp Exp $

PROG=	wall
SRCS=	wall.c ttymsg.c
BINGRP=	tty
BINMODE=2555
BINDIR	= /usr/bin
OPTIMIZE=79
HAS_BSD_MANPAGE	= true

.INCLUDE: /src/gno/prog.mk
