#	@(#)Makefile	8.1 (Berkeley) 6/6/93
#	$Id: Makefile,v 1.2 1998/03/11 03:10:31 gdr-ftp Exp $

PROG=	wall
SRCS=	wall.c ttymsg.c
BINGRP=	tty
BINMODE=2555
BINDIR	= /usr/bin
OPTIMIZE=79

.INCLUDE: /src/gno/prog.mk
