#
# gno/lib/libc/stdlib/Makefile
#
# $Id: Makefile,v 1.5 1998/02/09 08:44:55 taubert Exp $
#

LIB=	c
LIBPFX=	$(OBJ_DIR)../
OBJS=	cvt.o environ.o fpspecnum.o getopt.o getsubopt.o

.INCLUDE: /src/gno/lib/lib.mk

fpspecnum.o::	fpspecnum.mac
