#
# gno/lib/libc/stdlib/Makefile
#
# $Id: Makefile,v 1.6 1998/02/19 01:07:39 gdr-ftp Exp $
#

LIB	= c
LIBPFX	= $(OBJ_DIR)../
NO_REZ	= true
SRCS	= cvt.c environ.c fpspecnum.asm getopt.c getsubopt.c

.INCLUDE: /src/gno/lib/lib.mk

fpspecnum.o:	fpspecnum.mac
