.TH DESCC 8 "System Administration" "7 May 1995" "Version 1.0.3"
.SH NAME
descc \- the describe(1) source compiler
.SH SYNOPSIS
.BR descc " [" -hV ]
.I sourcefile
.SH DESCRIPTION
.BR descc
compiles the describe source file
.I sourcefile
and saves the result to the system describe database.
.SH OPTIONS
.nf
\fB-h\fR	Show usage information.

\fB-V\fR	Show version information.
.fi
.SH "FILE FORMATS"
The describe source file consists of comments and records.  A comment
is any line starting with the
.BR #
character.  Each record consists of eight fields.  The first 
seven consist of one line of text and begin with the following identifiers:
.nf

        Name:    (The name of the program.)
        Version: (The current version number.)
        Shell:   (The shell(s) the program was written for.)
        Author:  (The author or maintainer of the program.)
        Contact: (How to contact the Author, typically an 
                  email address.)
        Where:   (Where the program should be installed.)
        FTP:     (An ftp site from which the program may be
                  obtained.)

.fi
The last field consists of multiple lines of text.  It should be
a brief description of the program.  The following is an example of
a complete record:
.nf

        Name:    describe
        Version: 1.0.3
        Shell:   ORCA/Shell, GNO/ME
        Author:  James Brookes
        Contact: jamesb@ecst.csuchico.edu
        Where:   /usr/local/bin
        FTP:     ftp.cco.caltech.edu

           Print a multi-line description obtained from the compiled
        'describe' database; giving utility name, version, intended shell,
        author, author's contact, where the utility is, as well as where the
        utility can be FTPd from on the InterNet.

.fi
.LP
The describe database file consists of a 
.BR Header ,
a set of
.BR "Name Entries" ,
and a set of
.BR Records ,
in the following format:
.nf

        Header
           2 bytes:  Short Int, number of \fBName Entries\fR

        Name Entries
          34 bytes:  NULL-terminated string; name of the utility.
           4 bytes:  Long Int, offset of the \fBrecord\fR in file.

        Records
           8 variable-length NULL-terminated strings.

.fi
.SH FILES
/usr/local/lib/describe \- the system
.B describe
database. If the environment variable
.B DESCDB
is set, its value will be used instead.
.SH ENVIRONMENT
.IP DESCDB
Full path to the system describe database. If
.B DESCDB
is set, its value is used instead of the default location
/usr/local/lib/describe.

.SH AUTHOR
James Brookes <jamesb@ecst.csuchico.edu>.
.SH "SEE ALSO"
.BR apropos (1),
.BR describe (1),
.BR man (1),
.BR whatis (1),
.BR descu (8).
