.TH DESCU 8 "System Administration" "7 May 1995" "Version 1.0"
.SH NAME
descu \- the describe(1) source updater
.SH SYNOPSIS
.BR descu " [" -hV ]
.I sourcefile
.I patchfile1
[
.IR patchfile2 " ..."
]
.SH DESCRIPTION
.BR descu
updates the describe source file
.I sourcefile
by applying the new and updated records from the \fIpatchfile\fRs
and prints the result to standard output.
.LP
.IR Patchfile s
are just one or more describe source entries as defined in
.BR descc (8).
(They have nothing to do with
.BR patch (1).)
.LP
.IR Patchfile s
are assumed to contain at most one entry (in all listed
.IR patchfile s)
for a given program, keyed on the
.BR Name:
field.  If an entry in
.IR patchfile
is already in
.IR sourcefile ,
it replaces the original; otherwise the entry is appended.  In both
cases, the output is sorted lexicographically, based on the
.BR Name:
field.
.LP
.BR descu
will create the file
.B describe.rej
in the current directory.  This contains all records that were removed
from 
.IR sourcefile .
.SH OPTIONS
.nf
\fB-h\fR	Show usage information.

\fB-V\fR	Show version information.
.fi
.SH AUTHOR
Devin Reade <gdr@myrias.ab.ca>
.SH "SEE ALSO"
.BR apropos (1),
.BR describe (1),
.BR man (1),
.BR whatis (1),
.BR descc (8).
