.\"
.\" $Id: describe.1,v 1.4 1997/09/24 06:34:58 gdr Exp $
.\"
.TH DESCRIBE 1 "22 September 1997" GNO "Commands and Applications"
.SH NAME
describe \- show information about a program
.SH SYNOPSIS
.BR describe
[
.BR -hvV
]
.I program
.SH DESCRIPTION
This manual page documents
.BR describe
version 1.0.4.
.LP
.BR describe
will show current information about
.IR program .
This information includes:
.nf

	The name of the program;
	The program version number;
	The shell the program was written for;
	The author (or the person currently maintaining the program);
	Contact information for the author;
	Where the utility should be installed;
	An FTP site from which the program may be obtained, and;
	A brief description of the program.

.fi
.LP
.BR describe
uses a database compiled by
.BR descc (8).
.SH OPTIONS
.nf
\fB-h\fR	Show usage information.

\fB-v\fR	Verbose debugging mode.

\fB-V\fR	Show version information.
.fi
.SH FILES
.IP \fB/usr/lib/describe\fR
The system
.B describe
database. If the environment variable
.B DESCDB
is set, its value will be used instead.
.SH ENVIRONMENT
.IP DESCDB
Full path to the system describe database. If
.B DESCDB
is set, its value is used instead of the default location
.BR /usr/lib/describe .
.SH AUTHOR
James Brookes <jamesb@ecst.csuchico.edu>.
.SH "SEE ALSO"
.BR apropos (1),
.BR man (1),
.BR whatis (1),
.BR descc (8),
.BR descu (8).
