.TH DESCRIBE 1 "Commands and Applications" "7 May 1995" "Version 1.0.1"
.SH NAME
describe \- show information about a program
.SH SYNOPSIS
.BR describe " [" -hvV ]
.I program
.SH DESCRIPTION
.BR describe
will show current information about
.IR program .
This information includes:
.nf

	The name of the program;
	The program version number;
	The author (or the person currently maintaining the program);
	Contact information for the author;
	Where the utility should be installed;
	An FTP site from which the program may be obtained, and;
	A brief description of the program.

.fi
.LP
.BR describe
uses a database compiled by
.BR descc (8).
.SH OPTIONS
.nf
\fB-h\fR	Show usage information.

\fB-v\fR	Verbose debugging mode.

\fB-V\fR	Show version information.
.fi
.SH FILES
/usr/local/lib/describe \- the system
.B describe
database.
.SH AUTHOR
James Brookes <jamesb@ecst.csuchico.edu>.
.SH "SEE ALSO"
.BR apropos (1),
.BR man (1),
.BR whatis (1),
.BR descc (8),
.BR descu (8).
