.\"
.\" $Id: descc.8,v 1.6 1998/01/17 07:20:07 gdr Exp $
.\"
.TH DESCC 8 "22 September 1997" GNO "System Administration"
.SH NAME
descc \- the describe(1) source compiler
.SH SYNOPSIS
.BR descc
[
.BR -hV
]
.I sourcefile
.SH DESCRIPTION
This manual page documents
.BR descc
version 1.0.5.
.LP
.BR descc
compiles the describe source file
.I sourcefile
and saves the result to the system describe database.
If the database doesn't exist, or doesn't have type BIN, then
.BR descc
will set the database file type to BIN and the auxtype to 0x0000 after
it has been updated.
.SH OPTIONS
.nf
\fB-h\fR	Show usage information.

\fB-V\fR	Show version information.
.fi
.SH "FILE FORMATS"
The describe source file consists of comments and records.  A comment
is any line starting with the
.BR #
character.  Each record consists of eight fields.  The first 
seven consist of one line of text and begin with the following identifiers:
.nf

        Name:    (The name of the program.)
        Version: (The current version number.)
        Shell:   (The shell(s) the program was written for.)
        Author:  (The author or maintainer of the program.)
        Contact: (How to contact the Author, typically an 
                  email address.)
        Where:   (Where the program should be installed.)
        FTP:     (An ftp site from which the program may be
                  obtained.)

.fi
The last field consists of multiple lines of text.  It should be
a brief description of the program.  The following is an example of
a complete record:
.RS
.nf

Name:    describe
Version: 1.0.5
Shell:   GNO, ORCA/Shell
Author:  James Brookes
Contact: jamesb@ecst.csuchico.edu
Where:   /usr/bin
FTP:     apple2.caltech.edu, ground.isca.uiowa.edu

.fi
Print a multi-line description obtained from the compiled 'describe'
database; giving utility name, version, intended shell, author,
author's contact, where the utility is, as well as where the
utility can be FTPd from on the InterNet.
.RE
.LP
The describe database file consists of a 
.BR Header ,
a set of
.BR "Name Entries" ,
and a set of
.BR Records ,
in the following format:
.nf

        Header
           2 bytes:  Short Int, number of \fBName Entries\fR

        Name Entries
          36 bytes:  NULL-terminated string; name of the utility.
           4 bytes:  Long Int, offset of the \fBrecord\fR in file.

        Records
           8 variable-length NULL-terminated strings.

.fi
.SH FILES
.IP \fB/usr/lib/describe.db\fR
The system
.B describe
database. If the environment variable
.B DESCDB
is set, its value will be used instead.
.SH ENVIRONMENT
.IP DESCDB
Full path to the system describe database. If
.B DESCDB
is set, its value is used instead of the default location
.BR /usr/lib/describe.db .
.SH AUTHOR    
James Brookes <jamesb@ecst.csuchico.edu>.
.SH HISTORY
.BR descu
was incorporated into the GNO base distribution as of version 1.0.4
.SH "SEE ALSO"
.BR apropos (1),
.BR describe (1),
.BR man (1),
.BR whatis (1),
.BR descu (8).
