#
# $Id: Makefile,v 1.3 1999/02/15 19:08:46 gdr-ftp Exp $
#

PROG	= compile
BINDIR	= /usr/bin

# CFLAGS	+= -D__STACK_CHECK__
STACK	= 1024
OPTIMIZE= 79

HAS_MKSO_DATA	= true
HAS_MKLINK_DATA	= true

.INCLUDE : /src/gno/prog.mk

