#
# $Id: Makefile,v 1.2 1998/04/22 05:22:39 gdr-ftp Exp $
#

PROG	= compile
BINDIR	= /usr/bin

# CFLAGS	+= -D__STACK_CHECK__
STACK	= 1024
OPTIMIZE= 79

HAS_MKSO_DATA	= true

.INCLUDE : /src/gno/prog.mk

