.\" $Id: renram5.8,v 1.3 1998/03/31 03:29:06 gdr-ftp Exp $
.\"
.TH RENRAM5 8 "3 August 1997" GNO "System Administration"
.SH NAME
renram5 \- rename /RAM5 at boot time
.SH SYNOPSIS
.BR renram5
[
.B \-d
] [
.I oldvolume
[
.I newvolume
]]
.SH DESCRIPTION
.BR renram5
is intended to be run automatically at boot time.  It renames
the volume
.I oldvolume
to
.IR newvolume ,
if
.I newvolume
does not already exist.  If
.I oldvolume
or
.I newvolume
aren't specified, they default to
.BR /RAM5
and
.BR /tmp .
.LP
If you are running
.BR renram5
automatically from ProSel-16 (and perhaps other launchers) you should
change the filetype to
.BR S16 .
This will keep ProSel from prompting after the program is finished.
When run as a
.BR S16
program, no command line arguments are possible.
.SH OPTIONS
.IP \fB-d\fP
Enable debugging information.
.SH AUTHOR
Devin Reade, <gdr@trenco.gno.org>
.LP
This program is in the public domain.
.LP
This program contains material from the ORCA/C Run-Time
Libraries, copyright 1987-1997 by Byte Words, Inc.
Used with permission.
