#
# This makefile is intended for use with dmake(1) on Apple IIGS
#
# $Id: Makefile,v 1.5 1998/03/08 17:43:43 gdr-ftp Exp $
#
#	Created by Dave Tribby, September 1997

# Program name
PROG	= lseg

# Default stack size and optimization (can be overridden by cmd line)
#   These values have been tested and certified as working
STACK		*= 1024
OPTIMIZE	*= -1
  
# Delivery directory
BINDIR	= /usr/bin

.INCLUDE : /src/gno/prog.mk
